### ISSUE TITLE
Library name mismatch in examples

### ISSUE THREAD

**Issue by gsarti** [g8a9/ferret#9]
Examples in the `explanation_examples.ipynb` notebook import `nlxplain`, which I presume was the old name for `ferret` since it cannot be found on PyPI. As such, they should be updated to reflect the latest version of the library.

**Comment by g8a9** [comment]
Good catch, thank you @gsarti! Yeah, our initial name was `nlxplain` but we all agree `ferret` is way better :)
I've updated the notebook under `examples/` which is now called `benchmark.ipynb`.

Due to the Italian summer you know well, we have been a bit busy in reorganizing and cleaning everything up. But you can expect new features rolling out in early September, with new notebooks and doc pages.
